### ISSUE TITLE
Tests don't run on windows

### ISSUE THREAD

**Issue by II-Day-II** [carterwsmith/se23-project2#33]
Inspecting the `test_output` variable shows that it is empty when the server is running on windows. This may be due to the fact "python3" isn't defined on my machine, so an easy solution could be to just decide whether or not the 3 is there based on what OS the server is running on, but it would be cleaner to just call pytest from the code directly.

**Comment by carterwsmith** [comment]
This is interesting because I have seen Sanjin, who is on windows, use `python3 -m pytest` which works fine. 

Calling pytest directly creates many errors with the variable imports in the test file. You can probably find a solution by looking at including args in the `pytest.main()` documentation
